esphome:
  name: h2o-flux-meter

esp8266:
  board: esp01_1m

web_server:
  port: 80

# Enable logging
logger:
  baud_rate: 0    #Desliga serial dos GPIO1

# Enable Home Assistant API
api:
  encryption:
    key: "MqB6bhrQvk0Vn3p6tyjbnzJqvEJ6u5GyfcfXzhneyCo="

ota:
  password: "28e1097d5e7b8527b177f6a5c3573e42"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 192.168.0.212 # era .162
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 8.8.8.8
    dns2: 192.168.0.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "h2o-flux-meter"
    password: "12345678"

#captive_portal:


#binary_sensor:
#  - platform: gpio
#    pin:
#      number: GPIO15
#      mode: INPUT_PULLUP
#      inverted: False
#    name: "Pump"
#    device_class: power
##    filters:
##      - delayed_on: 10ms


sensor:
  - platform: pulse_counter
    pin: GPIO4
    unit_of_measurement: 'l/min'
    id: water_usage
    name: 'Fluxo de água'
    update_interval: 5s
    filters:
      - lambda: return (x / 330); # 396 = 5,5 * 60 (https://www.openhacks.com/uploadsproductos/g3_4_water_flow_sensor_-_wiki.pdf)
#      - lambda: return (x / 396); # 396 = 6,6 * 60
  - platform: integration
    name: "Consumo total (litros)"
    unit_of_measurement: 'l'
    sensor: water_usage
    time_unit: min
  - platform: integration
    name: "Consumo total (metros cúbicos)"
    unit_of_measurement: 'm3'
    sensor: water_usage
    time_unit: min
    filters:
      - lambda: return (x / 1000);