esphome:
  name: living01

esp8266:
  board: esp01_1m
  
web_server:
  port: 80

# Enable logging
logger:
  baud_rate: 0    #Desliga serial dos GPIO1

# Enable Home Assistant API
api:
  encryption:
    key: "VcM4Cdn2D1yUUNB4SR+p3EyOU/LPHAp7Vbg2N6ctXqk="

ota:
  password: "80cd3726a15c892f21251df6c2626f74"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 192.168.0.213
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 8.8.8.8
    dns2: 192.168.0.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "living01"
    password: "12345678"

captive_portal:

# -------------------------------------- ESP8266 ----------------------------------------
# | D1M | GPIO | Input |   Output   |                       Notes                       |
# |-----|------|-------|------------|---------------------------------------------------|
# |  D3 |  00  |  P-UP |    OK      | connected to FLASH bttn, BOOT FAILS if pulled LOW | P2-VM
# |  TX |  01  | OK/TX |   *OK      | HIGH at boot, debug out boot, BOOT FAILS if P-LOW | not used in this project
# |  D4 |  02  |  P-UP |  OK/LED    | HIGH at boot, board LED, BOOT FAILS if P-LOW      |
# |  RX |  03  |  *OK  |  OK/RX     | HIGH at boot                                      |
# |  D2 |  04  |   OK  |    OK      | often used as SDA (I2C)                           |
# |  D1 |  05  |   OK  |    OK      | often used as SCL (I2C)                           |
# |     |  06  |   X   |    X       | connected to FLASH chip, NOT recommended to use   |
# |     |  09  |   X   |    X       | HIGH at boot                                      |
# |     |  10  |   X   |    X       | HIGH at boot                                      |
# |     |  11  |   X   |    X       | connected to FLASH chip, NOT recommended to use   |
# |  D6 |  12  |   OK  |    OK      | SPI (MISO), can output a low signal at boot       |
# |  D7 |  13  |   OK  |    OK      | SPI (MOSI), can output a low signal at boot       |
# |  D5 |  14  |   OK  |    OK      | SPI (SCLK), can output a low signal at boot       |
# |  D8 |  15  | P-GND |   *OK      | SPI (CS), BOOT FAILS if pulled HIGH               |
# |  D0 |  16  | NoInt | No PWM/I2C | HIGH at boot, used to wake up from deep sleep     |
# |  A0 | ADC0 | AD In |    X       | Analog Input only  0 to 3.3v                      |
# ---------------------------------------------------------------------------------------

################################# BOTOES ###################################

binary_sensor:
  - platform: gpio   # ----------------BTN 1-----------
    pin:
      number: GPIO3 # RX VD-P2 com A.Optico
      mode:
        input: true
        pullup: true
      inverted: true
    name: "BTN1-abc"
#------------------------------------------------
    on_multi_click:
      - timing:
          - ON for 40ms to 400ms
          - OFF for at least 330ms
        then:
           - light.toggle: triac1_liv_stairs

      - timing:
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for at least 330ms
        then:
          light.toggle: triac2_liv_right

      - timing:
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for at least 50ms
        then:
         light.toggle: triac3_liv_back


  - platform: gpio   # ----------------BTN 4-----------
    pin:
#      number: GPIO5 # D1 AM-P2 com R2 montado (Bomba)
      number: GPIO0 # D3 VM-P2 (Bomba) {connected to FLASH bttn, BOOT FAILS if pulled LOW} **** Teste GPIO5 <=> GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "BTN4"
    on_press:
#      - light.toggle: triac6_s_garden_pot_pump
      - switch.toggle: triac6_side_garden_pot_pump

  - platform: gpio   # ----------------BTN 5-----------
    pin:
      number: GPIO4 # D2 BR-P2 (luzes solo/muro)
      mode:
        input: true
        pullup: true
      inverted: true
    name: "BTN5"
#    on_press:
#      - light.toggle: triac5_s_garden_soil_spots
#------------------------------------------------
    on_multi_click:
      - timing:
          - ON for 40ms to 400ms
          - OFF for at least 330ms
        then:
           - light.toggle: triac5_s_garden_soil_spots

      - timing:
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for at least 330ms
        then:
           - light.toggle: triac4_wall_right

#------------------------------------------------

light:
  - platform: binary
    name: "luz escada da sala"
    id: triac1_liv_stairs
    output: triac1_living_stairs
    icon: "mdi:lightbulb-spot"

  - platform: binary
    name: "luzes lateral da sala"
    id: triac2_liv_right
    output: triac2_living_right
    icon: "mdi:lightbulb-spot"

  - platform: binary
    name: "luzes fundo da sala"
    id: triac3_liv_back
    output: triac3_living_back
    icon: "mdi:lightbulb-spot"

  - platform: binary
    name: "iluminação do Muro direito"
    id: triac4_wall_right
    output: triac4_right_wall
    icon: "mdi:wall-sconce"

  - platform: binary
    name: "spot solo jardim lateral"
    id: triac5_s_garden_soil_spots
    output: triac5_side_garden_soil_spots
    icon: "mdi:lightbulb-spot"

#  - platform: binary
#    name: "bomba dos vasos jardim lateral"
#    id: triac6_s_garden_pot_pump
#    output: triac6_side_garden_pot_pump
#    icon: "mdi:fan"
  # -------------------------------------

output:
  - platform: gpio
    id: triac1_living_stairs
#    pin: GPIO0 # D3 VM-P2 {connected to FLASH bttn, BOOT FAILS if pulled LOW}
    pin: GPIO5 # D1 AM-P2 com R2 montado  **** Teste GPIO5 <=> GPIO0

  - platform: gpio
    id: triac2_living_right
    pin: GPIO13 # D7 BR-P1

  - platform: gpio
    id: triac3_living_back
    pin: GPIO12 # D6 VM-P1

  - platform: gpio
    id: triac4_right_wall
    pin: GPIO02 # D4 PT-P2 {HIGH at boot, board LED, BOOT FAILS if P-LOW}

  - platform: gpio
    id: triac5_side_garden_soil_spots
    pin:  GPIO14 # D5 PT-P1

 # - platform: gpio
 #   id: triac6_side_garden_pot_pump
 #   pin:  GPIO16
# --------------------------------------------------------------------------

switch:

  - platform: gpio
    name: "bomba dos vasos jardim lateral"
    icon: "mdi:fan"
    id: triac6_side_garden_pot_pump
#    pin: GPIO16 # D0 LR-P2 com R3 montado
    pin: GPIO15 # D8 AM-P1    => AZ-P2 (LED) com R6 Montado