esphome:
  name: office01
  friendly_name: office01

esp8266:
  board: esp01_1m

web_server:
  port: 80

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "I9dHOittlCi6XBVClguffVhTcWYxlvj6Zlh5r6xHlEQ="

ota:
  password: "a4d8bc43678b4c9ecc17b918fdce8b89"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 192.168.0.223
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 8.8.8.8
    dns2: 192.168.0.1
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "office01"
    password: "12345678"

captive_portal:
  
# -------------------------------------- ESP8266 ----------------------------------------
# | D1M | GPIO | Input |   Output   |                       Notes                       |
# |-----|------|-------|------------|---------------------------------------------------|
# |  D3 |  00  |  P-UP |    OK      | connected to FLASH bttn, BOOT FAILS if pulled LOW |
# |  TX |  01  | OK/TX |   *OK      | HIGH at boot, debug out boot, BOOT FAILS if P-LOW |
# |  D4 |  02  |  P-UP |  OK/LED    | HIGH at boot, board LED, BOOT FAILS if P-LOW      |
# |  RX |  03  |  *OK  |  OK/RX     | HIGH at boot                                      |
# |  D2 |  04  |   OK  |    OK      | often used as SDA (I2C)                           |
# |  D1 |  05  |   OK  |    OK      | often used as SCL (I2C)                           |
# |     | *06  |   X   |    X       | NOT WORK on ESPHome, connected to FLASH chip      |
# |     | *07  |   X   |    X       | NOT WORK on ESPHome, connected to FLASH chip      |
# |     | *08  |   X   |    X       | NOT WORK on ESPHome, connected to FLASH chip      |
# |     | *09  |   X   |    X       | NOT WORK on ESPHome, HIGH at boot                 |
# |     | ?10  |   ?   |    ?       | *NOT recommended to use, HIGH at boot*            |
# |     | *11  |   X   |    X       | NOT WORK on ESPHome, connected to FLASH chip      |
# |  D6 |  12  |   OK  |    OK      | SPI (MISO), can output a low signal at boot       |
# |  D7 |  13  |   OK  |    OK      | SPI (MOSI), can output a low signal at boot       |
# |  D5 |  14  |   OK  |    OK      | SPI (SCLK), can output a low signal at boot       |
# |  D8 |  15  | P-GND |   *OK      | SPI (CS), BOOT FAILS if pulled HIGH               |
# |  D0 |  16  | NoInt | No PWM/I2C | HIGH at boot, used to wake up from deep sleep     |
# |  A0 | ADC0 | AD In |    X       | Analog Input only  0 to 3.3v                      |
# ---------------------------------------------------------------------------------------

# -------------------------------------- OFFICE01 ---------------------------------------
# |  D0 |  16  |  IN              | Entrada com A/O interruptor da bancada              |
# |  D3 |  00  |  IN              | Interruptor 1 Luz Escritorio & Multi  (parede)      |
# |     | *10  |  IN              | Interruptor Pendentes                               |
# |  D6 |  12  |  IN              | Interruptor Exaustor                                |
# |  D2 |  04  | OUT              | Triac 4 - Luz Escritorio                            |
# |  D1 |  05  | OUT              | Triac 5 - Luz Pendentes                             |
# |  D8 |  15  | OUT              | Rele 15 - Exaustor                                  |
# |  D7 |  13  | OUT              | Triac Externo - Luz Bancada                         |
# |  D5 |  14  | OUT              | Triac Externo - Luz Armario                         |
# ---------------------------------------------------------------------------------------

output:
  
  # Register the blue LED as a dimmable output
  - platform: esp8266_pwm
    id: onboard_led
    pin:
      number: GPIO2 # Led Módulo
      inverted: true

  - platform: gpio # TRIAC On-Board
    id: "triac04"
    pin: GPIO5

  - platform: gpio # TRIAC On-Board
    id: "triac05"
    pin: GPIO4

  - platform: gpio
    id: "triac13"   # TRIAC Externo (Fio Azul CN2)
    pin: GPIO13
    inverted: true

  - platform: gpio
    id: "triac14"   # TRIAC Externo (Fio Verde CN2)
    pin: GPIO14
    inverted: true


light:

  # make a light out of it.
  - platform: monochromatic
    name: "Onboard LED"
    output: onboard_led
    id: led

  - platform: binary
    name: "Out 4 - Luz Parede" # Luz Escritorio
    id: triac_04
    output: triac04
    icon: "mdi:lightbulb-spot"

  - platform: binary
    name: "Out 5 - Pendentes" # Luz Pendentes Escritorio
    id: triac_05
    output: triac05
    icon: "mdi:lightbulb-spot"

  - platform: binary
    name: "Out 13 - Bancada"  # Luz Bancada Escritorio
    id: triac_13
    output: triac13
    icon: "mdi:lightbulb-spot"

  - platform: binary
    name: "Out 14 - Armario"  # Luz Armario Escritorio
    id: triac_14
    output: triac14
    icon: "mdi:lightbulb-spot"


switch:

  - platform: gpio
    name: "Out15 - Exaustor" # Rele On-Board
    icon: "mdi:fan"
    id: relay3_exhaust
    pin: GPIO15


sensor:
      
  - platform: uptime
    name: "Uptime"

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    
text_sensor:
  - platform: version
    name: "ESPHome Version"



binary_sensor:
  - platform: status
    name: "Status"


  - platform: gpio   # ---------------- BTN 1 (Porta) -----------
    pin:
      number: GPIO0 # Vermelho-CN3
      mode:
        input: true
        pullup: true
      inverted: true
    name: "BTN1-GPIO0-Porta"
#------------------------------------------------
    on_multi_click:
      - timing:
          - ON for 40ms to 400ms
          - OFF for at least 330ms
        then:
           - light.toggle: triac_04 #Luz Escritorio

      - timing:
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for at least 330ms
        then:
          light.toggle: triac_13  # Luz Bancada

      - timing:
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for at least 50ms
        then:
         light.toggle: triac_14  # Luz Armario

  - platform: gpio   # ----------------BTN 2 (Porta) -----------
    pin:
      number: GPIO10 # Azul-CN3
      mode:
        input: true
        pullup: true
      inverted: true
    name: "BTN2-GPIO10-Porta"
    on_press:
      - light.toggle: triac_05 # Pendentes

  - platform: gpio   # ----------------BTN 3 (Porta) -----------
    pin:
      number: GPIO12 # Laranja-CN2
      mode:
        input: true
        pullup: true
      inverted: true
    name: "BTN3-GPIO12-Porta"
    on_press:
      - switch.toggle: relay3_exhaust # Exaustor

  - platform: gpio   # ----------------BTN 4 (Bancada) -----------
    pin:
      number: GPIO16 # Branco-CN3
      mode:
        input: true
  #      pullup: true  # GPIO16 não suporta pullup
      inverted: true
    name: "BTN4-GPIO16-Bancada"

    on_multi_click:
      - timing:
          - ON for 40ms to 400ms
          - OFF for at least 330ms
        then:
           - light.toggle: triac_13 # Luz Bancada

      - timing:
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for at least 330ms
        then:
          light.toggle: triac_04 # Luz Escritorio

      - timing:
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for at least 50ms
        then:
         light.toggle: triac_05 # Pendentes

      - timing:
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for 40ms to 300ms
          - ON for 40ms to 400ms
          - OFF for at least 330ms
        then:
         light.toggle: triac_14  # Luz Armario