esphome:
  name: tst-ir-rec
  friendly_name: tst-ir-rec

esp8266:
  board: esp01_1m

web_server:
  port: 80

# Enable logging
logger:
  baud_rate: 0    #Desliga serial dos GPIO1

# Enable Home Assistant API
api:
  encryption:
    key: "rwfjCvcdlq/MQYyG903d2i6w28C42u2DDe1USHF3E2E="

ota:
  password: "923b4e7dfccade9ad62056002fa4905b"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 192.168.0.250
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 8.8.8.8
    dns2: 192.168.0.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "tstirrec"
    password: "12345678"

captive_portal:

# -------------------------------------- ESP8266 ----------------------------------------
# | D1M | GPIO | Input |   Output   |                       Notes                       |
# |-----|------|-------|------------|---------------------------------------------------|
# |  D3 |  00  |  P-UP |    OK      | connected to FLASH bttn, BOOT FAILS if pulled LOW |
# |  TX |  01  | OK/TX |   *OK      | HIGH at boot, debug out boot, BOOT FAILS if P-LOW |
# |  D4 |  02  |  P-UP |  OK/LED    | HIGH at boot, board LED, BOOT FAILS if P-LOW      |
# |  RX |  03  |  *OK  |  OK/RX     | HIGH at boot                                      |
# |  D2 |  04  |   OK  |    OK      | often used as SDA (I2C)                           |
# |  D1 |  05  |   OK  |    OK      | often used as SCL (I2C)                           |
# |     |  06  |   X   |    X       | connected to FLASH chip, NOT recommended to use   |
# |     |  09  |   X   |    X       | HIGH at boot                                      |
# |     |  10  |   X   |    X       | HIGH at boot                                      |
# |     |  11  |   X   |    X       | connected to FLASH chip, NOT recommended to use   |
# |  D6 |  12  |   OK  |    OK      | SPI (MISO), can output a low signal at boot       |
# |  D7 |  13  |   OK  |    OK      | SPI (MOSI), can output a low signal at boot       |
# |  D5 |  14  |   OK  |    OK      | SPI (SCLK), can output a low signal at boot       |
# |  D8 |  15  | P-GND |   *OK      | SPI (CS), BOOT FAILS if pulled HIGH               |
# |  D0 |  16  | NoInt | No PWM/I2C | HIGH at boot, used to wake up from deep sleep     |
# |  A0 | ADC0 | AD In |    X       | Analog Input only  0 to 3.3v                      |
# ---------------------------------------------------------------------------------------

remote_receiver:
  pin:
    number: GPIO4
    inverted: true
    mode:
      input: true
      pullup: true
  #dump: all
  #dump: raw
  dump: panasonic
  # [remote.panasonic:070] Received Panasonic: address=0x4004, command=0x011200BC
  #dump: nec
  #dump: aeha
  # [remote.aeha:099] Received AEHA: address=0x4004, data=[0x01,0x12,0x00,0xBC,0xAF] ok para projetor.

  # high 55% tolerance is recommended for some remote control units
  id: rcvr
  tolerance: 55%

climate:
  #- platform: coolix #Ar do escritorio
  - platform: climate_ir_lg
    name: "Home Theater AC"
    receiver_id: rcvr



# https://t-vk.github.io/Tasmota-IR-Code-Converter/ # Converte pronto data to tasmota.

remote_transmitter:
  pin: GPIO5
  carrier_duty_percent: 50%
#Adding a switch button to Lovelace to trigger:
switch:
  - platform: template
    name: Raw Code Power Button
    turn_on_action:
      - remote_transmitter.transmit_pronto:
          data: "0000 006D 003A 0000 0086 0042 0011 0010 0011 0031 0010 0011 0011 0010 0010 0011 0010 0011 0011 0010 0010 0011 0010 0011 0010 0011 0010 0011 0010 0011 0010 0011 0011 0031 0011 0010 0011 0010 0011 0010 0010 0011 0011 0010 0011 0010 0011 0010 0010 0011 0011 0010 0011 0031 0011 0010 0010 0011 0011 0010 0011 0031 0011 0010 0011 0010 0010 0032 0011 0010 0011 0010 0011 0010 0011 0010 0010 0011 0011 0011 0011 0010 0010 0011 0010 0011 0011 0031 0011 0010 0011 0031 0011 0031 0011 0031 0012 0031 0011 0010 0011 0010 0011 0031 0012 0010 0011 0031 0012 0010 0011 0031 0012 0031 0013 002F 0013 0030 0011 0180 06C3"




#----------------------------------------------------------------

light:
  - platform: status_led
    name: "Switch state"
    pin: GPIO2