esphome:
  name: ld2410-teste-esp8266
  friendly_name: ld2410-teste-esp8266

esp8266:
  board: d1_mini

# Enable logging
logger:
#  baud_rate: 0

web_server:
  port: 80

# Enable Home Assistant API
api:
  encryption:
    key: "L+v+P9I5sy0zrNqP9P+V+GRHKPhBk1gq//HVzSFzOQ4="

ota:
  password: "8fa58fa22ce15e3983e79bb4b6716970"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: LIGHT

  manual_ip:
    static_ip: 192.168.0.252
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 8.8.8.8
    dns2: 192.168.0.1
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ld2410-teste-esp8266"
    password: "12345678"

captive_portal:

# -------------------------------------- ESP8266 ----------------------------------------
# | D1M | GPIO | Input |   Output   |                       Notes                       |
# |-----|------|-------|------------|---------------------------------------------------|
# |  D3 |  00  |  P-UP |    OK      | connected to FLASH bttn, BOOT FAILS if pulled LOW |
# |  TX |  01  | OK/TX |   *OK      | HIGH at boot, debug out boot, BOOT FAILS if P-LOW |
# |  D4 |  02  |  P-UP |  OK/LED    | HIGH at boot, board LED, BOOT FAILS if P-LOW      |
# |  RX |  03  |  *OK  |  OK/RX     | HIGH at boot                                      |
# |  D2 |  04  |   OK  |    OK      | often used as SDA (I2C)                           |
# |  D1 |  05  |   OK  |    OK      | often used as SCL (I2C)                           |
# |     | *06  |   X   |    X       | NOT WORK on ESPHome, connected to FLASH chip      |
# |     | *07  |   X   |    X       | NOT WORK on ESPHome, connected to FLASH chip      |
# |     | *08  |   X   |    X       | NOT WORK on ESPHome, connected to FLASH chip      |
# |     | *09  |   X   |    X       | NOT WORK on ESPHome, HIGH at boot                 |
# |     | ?10  |   ?   |    ?       | *NOT recommended to use, HIGH at boot*            |
# |     | *11  |   X   |    X       | NOT WORK on ESPHome, connected to FLASH chip      |
# |  D6 |  12  |   OK  |    OK      | SPI (MISO), can output a low signal at boot       |
# |  D7 |  13  |   OK  |    OK      | SPI (MOSI), can output a low signal at boot       |
# |  D5 |  14  |   OK  |    OK      | SPI (SCLK), can output a low signal at boot       |
# |  D8 |  15  | P-GND |   *OK      | SPI (CS), BOOT FAILS if pulled HIGH               |
# |  D0 |  16  | NoInt | No PWM/I2C | HIGH at boot, used to wake up from deep sleep     |
# |  A0 | ADC0 | AD In |    X       | Analog Input only  0 to 3.3v                      |
# ---------------------------------------------------------------------------------------

 # https://www.youtube.com/watch?v=l212Lvo1R6s&t=169s

light:
  - platform: binary
    name: "Blue Status Light"
    output: light_output
    id: led_light
    restore_mode: ALWAYS_OFF
 
output:
  - platform: gpio
    pin: GPIO2
    inverted: true
    id: light_output
 
uart:
  id: ld2410_uart
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 256000
  parity: NONE
  stop_bits: 1
 
ld2410:
  uart_id: ld2410_uart
  throttle: 1500ms
  id: ld2410_comp
 


binary_sensor:
 
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target