esphome:
  name: water-quality-btpx
  friendly_name: water-quality-btpx

esp32:
  board: esp32dev

  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"

web_server:
  port: 80

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "/LKlMP4g+8sZyqWltayWGM5FeluGaYUfhoeeZCuZjA8="

ota:
  password: "c25e0b407ea80ca7e12fd5ae0eb78b06"

wifi:
  ssid: !secret water-quality-btpx
  password: !secret wifi_password

  manual_ip:
    static_ip: 192.168.0.223
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 8.8.8.8
    dns2: 192.168.0.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Water-Quality"
    password: "12345678"

captive_portal:

dallas:
  - pin: GPIO19

sensor:
  - platform: dallas
    address: 0x1c0000031edd2a28
    name: "Water Temperature"